# Generated by Django 3.2.10 on 2022-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('plan_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Dish', 'Dish'), ('Electricity', 'Electricity')], max_length=20)),
                ('operator', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('days', models.CharField(max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
